spring:
  datasource:
    url: jdbc:h2:mem:Test_DB
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  application:
    name: ORDER-SERVICE

server:
  port: 9090
